---
- name: mounting share(s)
  mount:
    path: /var/www
    src: fs-0c3b6d2c585d05ef8:/
    fstype: efs
    opts: nosuid,noexec,defaults,tls,accesspoint=fsap-09408c80cc07595a8
    state: mounted

- name: install httpd on the webserver
  ansible.builtin.yum:
    enablerepo: "BaseOS,AppStream"
    name: "httpd"
    state: present

- name: install mod_ssl on the webserver
  ansible.builtin.yum:
    name: "mod_ssl"
    state: present 

- name: install PHP
  ansible.builtin.yum:
    name:
      - php 
      - php-mysqlnd
      - php-gd 
      - php-curl
      - php-common
      - php-fpm
      - php-mbstring
      - php-opcache 
      - php-xml
      - php-intl 
      - php-json
    state: present

- name: ensure php-fpm is started and enabled
  ansible.builtin.service:
     name: php-fpm
     state: reloaded
     enabled: yes
  notify: Restart php-fpm

- import_tasks: setup-site.yml

- import_tasks: setup-db.yml

- name: ensure httpd is started and enabled
  ansible.builtin.service:
     name: httpd 
     state: started 
     enabled: yes
  notify: Restart httpd

- name: ensure php-fpm is started and enabled
  ansible.builtin.service:
     name: php-fpm
     state: reloaded
     enabled: yes
  notify: Restart php-fpm